appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: AfeYakkAABqB/StR9WiTe7ccd1sCPzBPuLPk7w9F6J/sldwpQNVMfMoG/7scih8iG68F2+2iooGgEQlv3kvRycqDhFrTDvQrHm0SoGp5N1/f9fNqAKyxMcR2bNbP8QT6e7B1Wg8p8dST+b5et4s0y/moQiFU921Bm8cknWeN3REToW2YgsH89oWUWxnIpKB8NPR6bFUmBVmWNrGDDGFT98fFQInu28l2oJ1v3U6bjgsb+Auqin7f0Q6JlXOPvKcXcKXKV1WAj6IKpVdM7p9opP9R9QgZ1uC0ZG8OMdK/jtZYH6VKpTClycpKvrV6gPfghHT5uFqN/0WpmE95kX+E9C1Y1J8KWbfbGWRyQmAFPzjYT6vRNnEfwMJxW93NO5q+oUUNZ2fLiw8wlqdGeyBfUDPD0AT1GkzCJmmTq8e+7982EKg4g2Jdw1YKxLMWz5cI29ueqN7d+kGvttV0ktvAObtJmBXla9lc2NOfL/xz+/J6a8cG83U7uhTajBiLazg/BJhmRz/JGa1OAlhlG2cQiQu4rGVo5tCCLhdvGuzx9ifnn/3mjo16iFXkSUMf7K+1T6CIxfuSCUo3isZoSDSBR54R43o18Ly1E79abRSvXez+6fLgcTmgnKOvH1ZYObP/xcpE2JBz8/9E7TkuzmjG42GRv0DBtM6v5vxcYeAxz/s=
conda_forge_output_validation: true
